security:
    role_hierarchy:
        ROLE_MODERATEUR: [ROLE_USER]
        ROLE_ADMIN: [ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        jwt_users:
            lexik_jwt:
                class: App\Infrastructure\Symfony\Security\JwtAuthenticatedUser

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/_debug/shop/(_profiler|_wdt)/
            security: false
        main:
            stateless: true
            entry_point: jwt
            provider: jwt_users
            jwt: ~

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/health$, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
