services:
  nginx:
    ports:
      - "${NGINX_EXPOSED_PORT:-20910}:80"

###> doctrine/mongodb-odm-bundle ###
  mongodb:
    ports:
      - "${MONGODB_EXPOSED_PORT:-20912}:27017"
###< doctrine/mongodb-odm-bundle ###

  redis:
    ports:
      - "${REDIS_EXPOSED_PORT:-20913}:6379"
