user  nginx;
worker_processes auto;

events {
    worker_connections  4096;
    multi_accept on;
}

http {
    index         index.html index.htm index.php;

    include       /etc/nginx/mime.types;
    include       /etc/nginx/fastcgi.conf;
    default_type  application/octet-stream;

    tcp_nopush      on;
    server_tokens       off;
    gzip  on;

    include /etc/nginx/conf.d/*.conf;
    client_max_body_size 20M;
}
